version: '3'

tasks:
  backend:
    cmds:
      - cargo run {{.CLI_ARGS}}

  dev-fast:
    cmds:
      - cargo run --release

  optimize:
    cmds:
      - cargo run --profile deploy

  frontend:
    cmds:
      - bun run dev
    dir: ./frontend

  prod:
    cmds:
      - bun run build
      - bun run preview
    dir: ./frontend