version: '3'

tasks:
  run-backend:
    cmds:
      - cargo run {{.CLI_ARGS}}
  
  run-frontend:
    cmds:
      - bun run dev
    dir: ./frontend

  dev:
    cmds:
      - task: run-backend
      - task: run-frontend

  dev-release: 
    cmds:
      - task: run-backend -- --release
      - task: run-frontend

  release:
    cmds:
      - task: run-backend --release    
