version: '3'

tasks:
  backend:
    cmds:
      - cargo run {{.CLI_ARGS}}

  release:
    cmds:
      - task: backend --release
  
  frontend:
    cmds:
      - bun run dev
    dir: ./frontend

  dev:
    cmds:
      - task: run-backend
      - task: run-frontend

  dev-release:
    cmds:
      - task: run-backend -- --release
      - task: run-frontend
