name: Rust
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rs'

permissions:
  checks: write

jobs:
  linter:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6

      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: true
          cache-on-failure: true

      - name: Install and Cache Apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: nasm
          version: 1.0

      - name: Run linter (clippy action)
        env:
          SQLX_OFFLINE: true
        uses: clechasseur/rs-clippy-check@v5
        with:
          args: --workspace
          # args: --verbose -- -W warnings

  formatting:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6

      - name: Rustfmt Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          cache: true
          cache-on-failure: true

      - name: Rust fmt check
        uses: actions-rust-lang/rustfmt@v1

